# Generated by Django 4.1.3 on 2023-01-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_by', to='twitter.profile'),
        ),
    ]
