# Generated by Django 4.1.3 on 2023-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
